controller:
  # https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/#re-configure-ingress-nginx-controller
  metrics:
    enabled: true
    # controller.metrics.serviceMonitor.enabled
    serviceMonitor:
      enabled: true
      # controller.metrics.serviceMonitor.additionalLabels.release="prometheus"
      additionalLabels:
        release: "kube-prometheus-stack"
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  service:
    type: LoadBalancer
    externalTrafficPolicy: "Local"
    annotations:
      # AWS Load Balancer Controller Annotations
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

      # SSL Annotations
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${ssl_cert_arn}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    targetPorts:
      http: http
      https: http
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
