apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 2
    labels:
      app: kube-prometheus-stack-alertmanager
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 48.2.3
      chart: kube-prometheus-stack-48.2.3
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-alertmanager
    namespace: kube-prometheus-stack
    resourceVersion: "155852471"
    uid: f7002f4f-a3bd-457b-b76d-3db621b263e1
  spec:
    endpoints:
    - enableHttp2: true
      path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
    namespaceSelector:
      matchNames:
      - kube-prometheus-stack
    selector:
      matchLabels:
        app: kube-prometheus-stack-alertmanager
        release: kube-prometheus-stack
        self-monitor: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-apiserver
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 48.2.3
      chart: kube-prometheus-stack-48.2.3
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-apiserver
    namespace: kube-prometheus-stack
    resourceVersion: "155852486"
    uid: 93938140-2e1d-4c0e-9538-ba78a63d37c8
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      metricRelabelings:
      - action: drop
        regex: apiserver_request_duration_seconds_bucket;(0.15|0.2|0.3|0.35|0.4|0.45|0.6|0.7|0.8|0.9|1.25|1.5|1.75|2|3|3.5|4|4.5|6|7|8|9|15|25|40|50)
        sourceLabels:
        - __name__
        - le
      port: https
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: false
        serverName: kubernetes
    jobLabel: component
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-coredns
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 48.2.3
      chart: kube-prometheus-stack-48.2.3
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-coredns
    namespace: kube-prometheus-stack
    resourceVersion: "155852475"
    uid: 97ecebc5-d1d7-4868-a7b5-31c41dc93501
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: kube-prometheus-stack-coredns
        release: kube-prometheus-stack
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 10.0.2
      helm.sh/chart: grafana-6.58.6
    name: kube-prometheus-stack-grafana
    namespace: kube-prometheus-stack
    resourceVersion: "155852441"
    uid: 2b446500-0a7c-48f9-9fb6-d545a326df0b
  spec:
    endpoints:
    - honorLabels: true
      path: /metrics
      port: http-web
      scheme: http
      scrapeTimeout: 30s
    jobLabel: kube-prometheus-stack
    namespaceSelector:
      matchNames:
      - kube-prometheus-stack
    selector:
      matchLabels:
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/name: grafana
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-kube-proxy
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 48.2.3
      chart: kube-prometheus-stack-48.2.3
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-kube-proxy
    namespace: kube-prometheus-stack
    resourceVersion: "155852495"
    uid: c5afbbe1-2074-46e1-aab1-4e92af46edce
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: kube-prometheus-stack-kube-proxy
        release: kube-prometheus-stack
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.9.2
      helm.sh/chart: kube-state-metrics-5.10.1
      release: kube-prometheus-stack
    name: kube-prometheus-stack-kube-state-metrics
    namespace: kube-prometheus-stack
    resourceVersion: "155852455"
    uid: fd036564-ef24-4b33-a8f5-870fd241e099
  spec:
    endpoints:
    - honorLabels: true
      port: http
    jobLabel: app.kubernetes.io/name
    selector:
      matchLabels:
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/name: kube-state-metrics
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-kubelet
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 48.2.3
      chart: kube-prometheus-stack-48.2.3
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-kubelet
    namespace: kube-prometheus-stack
    resourceVersion: "155852523"
    uid: 29893ba4-1de1-458b-8ded-26a77a75d547
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      port: https-metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      metricRelabelings:
      - action: drop
        regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_memory_(mapped_file|swap)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_(file_descriptors|tasks_state|threads_max)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_spec.*
        sourceLabels:
        - __name__
      - action: drop
        regex: .+;
        sourceLabels:
        - id
        - pod
      path: /metrics/cadvisor
      port: https-metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      path: /metrics/probes
      port: https-metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    jobLabel: k8s-app
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app.kubernetes.io/name: kubelet
        k8s-app: kubelet
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-operator
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 48.2.3
      chart: kube-prometheus-stack-48.2.3
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-operator
    namespace: kube-prometheus-stack
    resourceVersion: "155852527"
    uid: 3dd7e419-69b8-474c-98df-257696af0bce
  spec:
    endpoints:
    - honorLabels: true
      port: https
      scheme: https
      tlsConfig:
        ca:
          secret:
            key: ca
            name: kube-prometheus-stack-admission
            optional: false
        serverName: kube-prometheus-stack-operator
    namespaceSelector:
      matchNames:
      - kube-prometheus-stack
    selector:
      matchLabels:
        app: kube-prometheus-stack-operator
        release: kube-prometheus-stack
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 2
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 48.2.3
      chart: kube-prometheus-stack-48.2.3
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-prometheus
    namespace: kube-prometheus-stack
    resourceVersion: "155852532"
    uid: a0315be7-3400-4950-9578-922b61835c00
  spec:
    endpoints:
    - path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
    namespaceSelector:
      matchNames:
      - kube-prometheus-stack
    selector:
      matchLabels:
        app: kube-prometheus-stack-prometheus
        release: kube-prometheus-stack
        self-monitor: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: kube-prometheus-stack
    creationTimestamp: "2023-06-18T04:36:27Z"
    generation: 1
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/part-of: prometheus-node-exporter
      app.kubernetes.io/version: 1.6.0
      helm.sh/chart: prometheus-node-exporter-4.21.0
      jobLabel: node-exporter
      release: kube-prometheus-stack
    name: kube-prometheus-stack-prometheus-node-exporter
    namespace: kube-prometheus-stack
    resourceVersion: "155852469"
    uid: 316453c4-91ac-4b1c-b6a9-adfc6ca381fc
  spec:
    endpoints:
    - port: http-metrics
      scheme: http
    jobLabel: jobLabel
    selector:
      matchLabels:
        app.kubernetes.io/instance: kube-prometheus-stack
        app.kubernetes.io/name: prometheus-node-exporter
kind: List
metadata:
  resourceVersion: ""
