apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-efa
  labels:
    vpc.amazonaws.com/efa.present: "true"
    nvidia.com/gpu.present: "true"
spec:
  template:
    metadata:
      labels:
        nvidia.com/gpu.present: "true"
        vpc.amazonaws.com/efa.present: "true"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu-efa
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        # values: [ "g5", "g5e", "g6e", "p4", "p5", "p5e", "p5en" ]
        values: [ "g6e", "p4", "p5", "p5e", "p5en" ]
      # - key: karpenter.k8s.aws/instance-size
      #   operator: In
      #   values: [ "8xlarge" ]
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: Exists
      - key: vpc.amazonaws.com/efa.present
        operator: Exists
      - key: kubernetes.io/arch
        operator: In
        values: [ "amd64" ]
      - key: karpenter.sh/capacity-type
        operator: In
        values: [ "spot", "on-demand" ]
      - key: "topology.kubernetes.io/zone"
        operator: In
        values: [ "us-west-2b" ]
      taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: "NoSchedule"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu-efa
spec:
  amiFamily: AL2023
  amiSelectorTerms:
  - alias: al2023@latest
  role: tf-eks-demo
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: tf-eks-demo
      # efa-supported: "true"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: tf-eks-demo
  tags:
    karpenter.sh/discovery: tf-eks-demo
  # blockDeviceMappings:
  # - deviceName: /dev/xvda
  #   ebs:
  #     volumeSize: "500Gi"
  #     volumeType: gp3
  #     encrypted: true
  instanceStorePolicy: RAID0
  detailedMonitoring: true
