gfd:
  enabled: true
nfd:
  enabled: true
  worker:
    tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - operator: "Exists"
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: nvidia.com/gpu
    #           operator: Exists
